CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Management') THEN
            CREATE SCHEMA "Management";
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."AspNetRoles" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "IsActive" boolean NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."HireTypes" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_HireTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."Permissions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."ShiftTypes" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "IsFlexibleExit" boolean NOT NULL,
        "Structure" integer NOT NULL,
        "SubType" integer,
        "Block1Start" interval,
        "Block1End" interval,
        "Block2Start" interval,
        "Block2End" interval,
        "finishNextDay" boolean NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_ShiftTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."WorkAreas" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_WorkAreas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Management"."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."AspNetUsers" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "FirstName" character varying(20),
        "LastName" character varying(20),
        "IsActive" boolean NOT NULL,
        "NickName" text NOT NULL,
        "HireDate" timestamp with time zone NOT NULL,
        "HireTypeId" uuid,
        "IsDelete" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUsers_HireTypes_HireTypeId" FOREIGN KEY ("HireTypeId") REFERENCES "Management"."HireTypes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."RolePermissions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "PermissionId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RolePermissions_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Management"."AspNetRoles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Management"."Permissions" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."Workstations" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "WorkAreaId" uuid NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Workstations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Workstations_WorkAreas_WorkAreaId" FOREIGN KEY ("WorkAreaId") REFERENCES "Management"."WorkAreas" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Management"."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."Licenses" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "Reason" text NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone NOT NULL,
        "IsHalfDay" boolean NOT NULL,
        "HalfPeriod" text,
        "DaysRequested" integer,
        "Observation" text,
        "IsDeleted" boolean NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Licenses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Licenses_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."UserActivityLogs" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "Action" text NOT NULL,
        "IpAddress" text NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_UserActivityLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserActivityLogs_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE TABLE "Management"."UserWorkstations" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "WorkstationId" uuid NOT NULL,
        "Covertage" integer NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_UserWorkstations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserWorkstations_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserWorkstations_Workstations_WorkstationId" FOREIGN KEY ("WorkstationId") REFERENCES "Management"."Workstations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "Management"."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "Management"."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "Management"."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "Management"."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "Management"."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "EmailIndex" ON "Management"."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_AspNetUsers_HireTypeId" ON "Management"."AspNetUsers" ("HireTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Management"."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_Licenses_UserId" ON "Management"."Licenses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_RolePermissions_PermissionId" ON "Management"."RolePermissions" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_RolePermissions_RoleId" ON "Management"."RolePermissions" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_UserActivityLogs_UserId" ON "Management"."UserActivityLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_UserWorkstations_UserId" ON "Management"."UserWorkstations" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_UserWorkstations_WorkstationId" ON "Management"."UserWorkstations" ("WorkstationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    CREATE INDEX "IX_Workstations_WorkAreaId" ON "Management"."Workstations" ("WorkAreaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250509014501_creationBase') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250509014501_creationBase', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510153555_hybridWorkStation') THEN
    CREATE TABLE "Management"."HybridWorkstations" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "WorkstationAId" uuid NOT NULL,
        "WorkstationBId" uuid NOT NULL,
        "Description" text,
        "IsDeleted" boolean NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_HybridWorkstations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_HybridWorkstations_Workstations_WorkstationAId" FOREIGN KEY ("WorkstationAId") REFERENCES "Management"."Workstations" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_HybridWorkstations_Workstations_WorkstationBId" FOREIGN KEY ("WorkstationBId") REFERENCES "Management"."Workstations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510153555_hybridWorkStation') THEN
    CREATE INDEX "IX_HybridWorkstations_WorkstationAId" ON "Management"."HybridWorkstations" ("WorkstationAId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510153555_hybridWorkStation') THEN
    CREATE INDEX "IX_HybridWorkstations_WorkstationBId" ON "Management"."HybridWorkstations" ("WorkstationBId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510153555_hybridWorkStation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250510153555_hybridWorkStation', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510155913_updateUserWorkStation') THEN
    ALTER TABLE "Management"."UserWorkstations" RENAME COLUMN "Covertage" TO "Coverage";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510155913_updateUserWorkStation') THEN
    ALTER TABLE "Management"."UserWorkstations" ADD "IsDelete" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250510155913_updateUserWorkStation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250510155913_updateUserWorkStation', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250512140714_addUserRestrictions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250512140714_addUserRestrictions', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250513014437_addRestriction') THEN
    CREATE TABLE "Management"."UserRestrictionShifts" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Observation" text NOT NULL,
        "IsDelete" boolean NOT NULL,
        "IsRestricted" boolean NOT NULL,
        "UserId" uuid NOT NULL,
        "ShiftTypeId" uuid NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_UserRestrictionShifts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserRestrictionShifts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserRestrictionShifts_ShiftTypes_ShiftTypeId" FOREIGN KEY ("ShiftTypeId") REFERENCES "Management"."ShiftTypes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250513014437_addRestriction') THEN
    CREATE INDEX "IX_UserRestrictionShifts_ShiftTypeId" ON "Management"."UserRestrictionShifts" ("ShiftTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250513014437_addRestriction') THEN
    CREATE INDEX "IX_UserRestrictionShifts_UserId" ON "Management"."UserRestrictionShifts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250513014437_addRestriction') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250513014437_addRestriction', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250516141417_addPropertiesUser') THEN
    ALTER TABLE "Management"."AspNetUsers" ADD "ComplementHours" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250516141417_addPropertiesUser') THEN
    ALTER TABLE "Management"."AspNetUsers" ADD "HiredHours" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250516141417_addPropertiesUser') THEN
    ALTER TABLE "Management"."AspNetUsers" ADD "LawApply" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250516141417_addPropertiesUser') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250516141417_addPropertiesUser', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521000717_updateUserAddExtraHours') THEN
    ALTER TABLE "Management"."UserRestrictionShifts" RENAME COLUMN "IsRestricted" TO "Work";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521000717_updateUserAddExtraHours') THEN
    ALTER TABLE "Management"."AspNetUsers" ADD "ExtraHours" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521000717_updateUserAddExtraHours') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521000717_updateUserAddExtraHours', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521001143_updateUserWorskStationPreference') THEN
    ALTER TABLE "Management"."UserWorkstations" ADD "Preference" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521001143_updateUserWorskStationPreference') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521001143_updateUserWorskStationPreference', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521135043_addEmployeeRestrictionWeek') THEN
    CREATE TABLE "Management"."EmployeeScheduleRestrictions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "DayOfWeek" integer NOT NULL,
        "RestrictionType" integer NOT NULL,
        "AvailableFrom" interval,
        "AvailableUntil" interval,
        "Block1Start" interval,
        "Block1End" interval,
        "Block2Start" interval,
        "Block2End" interval,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_EmployeeScheduleRestrictions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmployeeScheduleRestrictions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521135043_addEmployeeRestrictionWeek') THEN
    CREATE INDEX "IX_EmployeeScheduleRestrictions_UserId" ON "Management"."EmployeeScheduleRestrictions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521135043_addEmployeeRestrictionWeek') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521135043_addEmployeeRestrictionWeek', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521162408_addAbsenteeismType') THEN
    CREATE TABLE "Management"."AbsenteeismTypes" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_AbsenteeismTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521162408_addAbsenteeismType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521162408_addAbsenteeismType', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521164423_addUserAbsenteeism') THEN
    CREATE TABLE "Management"."UserAbsenteeisms" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "AbsenteeismTypeId" uuid NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "Observation" text,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_UserAbsenteeisms" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserAbsenteeisms_AbsenteeismTypes_AbsenteeismTypeId" FOREIGN KEY ("AbsenteeismTypeId") REFERENCES "Management"."AbsenteeismTypes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserAbsenteeisms_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521164423_addUserAbsenteeism') THEN
    CREATE INDEX "IX_UserAbsenteeisms_AbsenteeismTypeId" ON "Management"."UserAbsenteeisms" ("AbsenteeismTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521164423_addUserAbsenteeism') THEN
    CREATE INDEX "IX_UserAbsenteeisms_UserId" ON "Management"."UserAbsenteeisms" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250521164423_addUserAbsenteeism') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250521164423_addUserAbsenteeism', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250525144638_employeeExceptions') THEN
    CREATE TABLE "Management"."EmployeeScheduleExceptions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "Date" date NOT NULL,
        "RestrictionType" integer NOT NULL,
        "IsAdditionalRestriction" boolean NOT NULL,
        "AvailableFrom" interval,
        "AvailableUntil" interval,
        "Block1Start" interval,
        "Block1End" interval,
        "Block2Start" interval,
        "Block2End" interval,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_EmployeeScheduleExceptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmployeeScheduleExceptions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250525144638_employeeExceptions') THEN
    CREATE INDEX "IX_EmployeeScheduleExceptions_UserId" ON "Management"."EmployeeScheduleExceptions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250525144638_employeeExceptions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250525144638_employeeExceptions', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250603010124_addPropertiesUserCant') THEN
    ALTER TABLE "Management"."AspNetUsers" ADD "CantPartTimeSchedule" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250603010124_addPropertiesUserCant') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250603010124_addPropertiesUserCant', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250603012050_addLawRestriction') THEN
    CREATE TABLE "Management"."LawRestrictions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Description" text NOT NULL,
        "CantHours" integer NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_LawRestrictions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250603012050_addLawRestriction') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250603012050_addLawRestriction', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250605001530_addTemplateWorkStation') THEN
    CREATE TABLE "Management"."WorkstationDemandTemplates" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Name" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_WorkstationDemandTemplates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250605001530_addTemplateWorkStation') THEN
    CREATE TABLE "Management"."WorkstationDemands" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "TemplateId" uuid NOT NULL,
        "WorkstationId" uuid NOT NULL,
        "Day" integer NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "EffortRequired" double precision NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_WorkstationDemands" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WorkstationDemands_WorkstationDemandTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "Management"."WorkstationDemandTemplates" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_WorkstationDemands_Workstations_WorkstationId" FOREIGN KEY ("WorkstationId") REFERENCES "Management"."Workstations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250605001530_addTemplateWorkStation') THEN
    CREATE INDEX "IX_WorkstationDemands_TemplateId" ON "Management"."WorkstationDemands" ("TemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250605001530_addTemplateWorkStation') THEN
    CREATE INDEX "IX_WorkstationDemands_WorkstationId" ON "Management"."WorkstationDemands" ("WorkstationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250605001530_addTemplateWorkStation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250605001530_addTemplateWorkStation', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707115304_updateShiftType') THEN
    ALTER TABLE "Management"."ShiftTypes" DROP COLUMN "SubType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707115304_updateShiftType') THEN
    ALTER TABLE "Management"."ShiftTypes" RENAME COLUMN "IsFlexibleExit" TO "IsActive";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707115304_updateShiftType') THEN
    ALTER TABLE "Management"."ShiftTypes" RENAME COLUMN "Block2End" TO "Block2lastStart";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707115304_updateShiftType') THEN
    ALTER TABLE "Management"."ShiftTypes" RENAME COLUMN "Block1End" TO "Block1lastStart";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250707115304_updateShiftType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250707115304_updateShiftType', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250708155347_shiftTypeRestriction') THEN
    DROP TABLE "Management"."UserRestrictionShifts";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250708155347_shiftTypeRestriction') THEN
    CREATE TABLE "Management"."EmployeeShiftTypeRestrictions" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "DayOfWeek" integer NOT NULL,
        "ShiftTypeId" uuid NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_EmployeeShiftTypeRestrictions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EmployeeShiftTypeRestrictions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_EmployeeShiftTypeRestrictions_ShiftTypes_ShiftTypeId" FOREIGN KEY ("ShiftTypeId") REFERENCES "Management"."ShiftTypes" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250708155347_shiftTypeRestriction') THEN
    CREATE INDEX "IX_EmployeeShiftTypeRestrictions_ShiftTypeId" ON "Management"."EmployeeShiftTypeRestrictions" ("ShiftTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250708155347_shiftTypeRestriction') THEN
    CREATE INDEX "IX_EmployeeShiftTypeRestrictions_UserId" ON "Management"."EmployeeShiftTypeRestrictions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250708155347_shiftTypeRestriction') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250708155347_shiftTypeRestriction', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719174245_addForgot') THEN
    ALTER TABLE "Management"."AspNetUsers" ADD "PasswordResetToken" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719174245_addForgot') THEN
    ALTER TABLE "Management"."AspNetUsers" ADD "PasswordResetTokenExpiration" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250719174245_addForgot') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250719174245_addForgot', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720224236_updateWorkstations') THEN
    ALTER TABLE "Management"."HybridWorkstations" ADD "WorkstationCId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720224236_updateWorkstations') THEN
    ALTER TABLE "Management"."HybridWorkstations" ADD "WorkstationDId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720224236_updateWorkstations') THEN
    CREATE INDEX "IX_HybridWorkstations_WorkstationCId" ON "Management"."HybridWorkstations" ("WorkstationCId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720224236_updateWorkstations') THEN
    CREATE INDEX "IX_HybridWorkstations_WorkstationDId" ON "Management"."HybridWorkstations" ("WorkstationDId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720224236_updateWorkstations') THEN
    ALTER TABLE "Management"."HybridWorkstations" ADD CONSTRAINT "FK_HybridWorkstations_Workstations_WorkstationCId" FOREIGN KEY ("WorkstationCId") REFERENCES "Management"."Workstations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720224236_updateWorkstations') THEN
    ALTER TABLE "Management"."HybridWorkstations" ADD CONSTRAINT "FK_HybridWorkstations_Workstations_WorkstationDId" FOREIGN KEY ("WorkstationDId") REFERENCES "Management"."Workstations" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720224236_updateWorkstations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250720224236_updateWorkstations', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720232016_schedule') THEN
    CREATE TABLE "Management"."Schedules" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "Date" date NOT NULL,
        "UserId" uuid NOT NULL,
        "WorkstationId" uuid NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "Observation" text,
        "IsDeleted" boolean NOT NULL,
        "IdUpdate" text,
        "DateUpdate" timestamp with time zone,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Schedules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Schedules_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Schedules_Workstations_WorkstationId" FOREIGN KEY ("WorkstationId") REFERENCES "Management"."Workstations" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720232016_schedule') THEN
    CREATE INDEX "IX_Schedules_UserId" ON "Management"."Schedules" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720232016_schedule') THEN
    CREATE INDEX "IX_Schedules_WorkstationId" ON "Management"."Schedules" ("WorkstationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250720232016_schedule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250720232016_schedule', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725014551_userShiftResolve') THEN
    ALTER TABLE "Management"."Licenses" ALTER COLUMN "DateCreated" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725014551_userShiftResolve') THEN
    ALTER TABLE "Management"."Licenses" ALTER COLUMN "Id" DROP DEFAULT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725014551_userShiftResolve') THEN
    CREATE TABLE "Management"."UserShifts" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "Day" integer NOT NULL,
        "Structure" integer NOT NULL,
        "Block1Start" interval,
        "Block1lastStart" interval,
        "Block2Start" interval,
        "Block2lastStart" interval,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_UserShifts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserShifts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725014551_userShiftResolve') THEN
    CREATE INDEX "IX_UserShifts_UserId" ON "Management"."UserShifts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250725014551_userShiftResolve') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250725014551_userShiftResolve', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250728215711_alterSchedule') THEN
    ALTER TABLE "Management"."Schedules" ALTER COLUMN "StartTime" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250728215711_alterSchedule') THEN
    ALTER TABLE "Management"."Schedules" ALTER COLUMN "EndTime" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250728215711_alterSchedule') THEN
    ALTER TABLE "Management"."Schedules" ADD "Notified" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250728215711_alterSchedule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250728215711_alterSchedule', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250731125231_addfieldsData') THEN
    ALTER TABLE "Management"."WorkstationDemandTemplates" ADD "EndDate" date NOT NULL DEFAULT DATE '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250731125231_addfieldsData') THEN
    ALTER TABLE "Management"."WorkstationDemandTemplates" ADD "StartDate" date NOT NULL DEFAULT DATE '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250731125231_addfieldsData') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250731125231_addfieldsData', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250815015403_addPropertiesSchedule') THEN
    ALTER TABLE "Management"."Schedules" ADD "Token" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250815015403_addPropertiesSchedule') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250815015403_addPropertiesSchedule', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250815200751_addNullableRelation') THEN
    ALTER TABLE "Management"."Schedules" ALTER COLUMN "WorkstationId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250815200751_addNullableRelation') THEN
    CREATE TABLE "Management"."SigningCofigurations" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        email text NOT NULL,
        description text,
        "isAdminMail" boolean NOT NULL,
        "WorkArea" text NOT NULL,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_SigningCofigurations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250815200751_addNullableRelation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250815200751_addNullableRelation', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250819165824_addColorWorkArea') THEN
    ALTER TABLE "Management"."WorkAreas" ADD "Color" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250819165824_addColorWorkArea') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250819165824_addColorWorkArea', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250828030910_addSigning') THEN
    CREATE TABLE "Management"."Signings" (
        "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "UserId" uuid NOT NULL,
        "Date" date NOT NULL,
        "StartTime" time without time zone NOT NULL,
        "EndTime" time without time zone,
        "TipoFichaje" integer NOT NULL,
        "Observaciones" text NOT NULL,
        "LastUpdateUserId" uuid NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "DateCreated" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_Signings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Signings_AspNetUsers_LastUpdateUserId" FOREIGN KEY ("LastUpdateUserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Signings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "Management"."AspNetUsers" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250828030910_addSigning') THEN
    CREATE INDEX "IX_Signings_LastUpdateUserId" ON "Management"."Signings" ("LastUpdateUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250828030910_addSigning') THEN
    CREATE INDEX "IX_Signings_UserId" ON "Management"."Signings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250828030910_addSigning') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250828030910_addSigning', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250831192305_updateSigning') THEN
    ALTER TABLE "Management"."Signings" ALTER COLUMN "LastUpdateUserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250831192305_updateSigning') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250831192305_updateSigning', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113125107_ChangeDateTimeToDateOnlyInUserAbsenteeism') THEN
    ALTER TABLE "Management"."UserAbsenteeisms" ALTER COLUMN "StartDate" TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113125107_ChangeDateTimeToDateOnlyInUserAbsenteeism') THEN
    ALTER TABLE "Management"."UserAbsenteeisms" ALTER COLUMN "EndDate" TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251113125107_ChangeDateTimeToDateOnlyInUserAbsenteeism') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251113125107_ChangeDateTimeToDateOnlyInUserAbsenteeism', '8.0.11');
    END IF;
END $EF$;
COMMIT;

